# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 1091, 771))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 1061, 302))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.bearing_lineEdit_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_d.setObjectName("bearing_lineEdit_d")
        self.horizontalLayout_3.addWidget(self.bearing_lineEdit_d)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.bearing_lineEdit_D = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_D.setObjectName("bearing_lineEdit_D")
        self.horizontalLayout_3.addWidget(self.bearing_lineEdit_D)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.bearing_lineEdit_B = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_B.setObjectName("bearing_lineEdit_B")
        self.horizontalLayout_3.addWidget(self.bearing_lineEdit_B)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.bearing_lineEdit_C = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_C.setObjectName("bearing_lineEdit_C")
        self.horizontalLayout_3.addWidget(self.bearing_lineEdit_C)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.bearing_lineEdit_P_radial = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_P_radial.setObjectName("bearing_lineEdit_P_radial")
        self.horizontalLayout_3.addWidget(self.bearing_lineEdit_P_radial)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.bearing_lineEdit_P_axial = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_P_axial.setObjectName("bearing_lineEdit_P_axial")
        self.horizontalLayout_3.addWidget(self.bearing_lineEdit_P_axial)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.bearing_lineEdit_P_radial_applied = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_P_radial_applied.setObjectName("bearing_lineEdit_P_radial_applied")
        self.horizontalLayout_5.addWidget(self.bearing_lineEdit_P_radial_applied)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.bearing_lineEdit_FF = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_FF.setObjectName("bearing_lineEdit_FF")
        self.horizontalLayout_5.addWidget(self.bearing_lineEdit_FF)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_7.addWidget(self.label_32)
        self.bearing_lineEdit_excel_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit_excel_input.setObjectName("bearing_lineEdit_excel_input")
        self.horizontalLayout_7.addWidget(self.bearing_lineEdit_excel_input)
        self.bearing_toolButton_excel_input = QtWidgets.QToolButton(self.verticalLayoutWidget_3)
        self.bearing_toolButton_excel_input.setObjectName("bearing_toolButton_excel_input")
        self.horizontalLayout_7.addWidget(self.bearing_toolButton_excel_input)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.bearing_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.bearing_pushButton.setObjectName("bearing_pushButton")
        self.verticalLayout_3.addWidget(self.bearing_pushButton)
        self.bearing_tableWidget_results = QtWidgets.QTableWidget(self.tab_2)
        self.bearing_tableWidget_results.setGeometry(QtCore.QRect(10, 340, 1061, 381))
        self.bearing_tableWidget_results.setObjectName("bearing_tableWidget_results")
        self.bearing_tableWidget_results.setColumnCount(0)
        self.bearing_tableWidget_results.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(20, 480, 81, 16))
        self.label_34.setObjectName("label_34")
        self.plain_bushing_lineEdit_excel_input = QtWidgets.QLineEdit(self.tab_3)
        self.plain_bushing_lineEdit_excel_input.setGeometry(QtCore.QRect(20, 500, 151, 22))
        self.plain_bushing_lineEdit_excel_input.setObjectName("plain_bushing_lineEdit_excel_input")
        self.plain_bushing_toolButton_excel_input = QtWidgets.QToolButton(self.tab_3)
        self.plain_bushing_toolButton_excel_input.setGeometry(QtCore.QRect(180, 500, 27, 22))
        self.plain_bushing_toolButton_excel_input.setObjectName("plain_bushing_toolButton_excel_input")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 180, 231))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_4.addWidget(self.label_37)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.plain_bushing_lineEdit_Fcy = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.plain_bushing_lineEdit_Fcy.setObjectName("plain_bushing_lineEdit_Fcy")
        self.horizontalLayout_6.addWidget(self.plain_bushing_lineEdit_Fcy)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_4.addWidget(self.label_38)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.plain_bushing_lineEdit_tb = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.plain_bushing_lineEdit_tb.setObjectName("plain_bushing_lineEdit_tb")
        self.horizontalLayout_13.addWidget(self.plain_bushing_lineEdit_tb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_4.addWidget(self.label_39)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_14.addWidget(self.label_41)
        self.plain_bushing_lineEdit_tf = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.plain_bushing_lineEdit_tf.setObjectName("plain_bushing_lineEdit_tf")
        self.horizontalLayout_14.addWidget(self.plain_bushing_lineEdit_tf)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.label_43 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.label_43)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_44 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_21.addWidget(self.label_44)
        self.plain_bushing_lineEdit_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.plain_bushing_lineEdit_d.setObjectName("plain_bushing_lineEdit_d")
        self.horizontalLayout_21.addWidget(self.plain_bushing_lineEdit_d)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 340, 181, 121))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_23.addWidget(self.label_36)
        self.plain_bushing_lineEdit_P_limit_applied = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.plain_bushing_lineEdit_P_limit_applied.setObjectName("plain_bushing_lineEdit_P_limit_applied")
        self.horizontalLayout_23.addWidget(self.plain_bushing_lineEdit_P_limit_applied)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_47 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_24.addWidget(self.label_47)
        self.plain_bushing_lineEdit_FF = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.plain_bushing_lineEdit_FF.setObjectName("plain_bushing_lineEdit_FF")
        self.horizontalLayout_24.addWidget(self.plain_bushing_lineEdit_FF)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.plain_bushing_pushButton = QtWidgets.QPushButton(self.tab_3)
        self.plain_bushing_pushButton.setGeometry(QtCore.QRect(20, 540, 181, 28))
        self.plain_bushing_pushButton.setObjectName("plain_bushing_pushButton")
        self.plain_bushing_tableWidget_results = QtWidgets.QTableWidget(self.tab_3)
        self.plain_bushing_tableWidget_results.setGeometry(QtCore.QRect(220, 30, 851, 531))
        self.plain_bushing_tableWidget_results.setObjectName("plain_bushing_tableWidget_results")
        self.plain_bushing_tableWidget_results.setColumnCount(0)
        self.plain_bushing_tableWidget_results.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_84 = QtWidgets.QLabel(self.tab_7)
        self.label_84.setGeometry(QtCore.QRect(40, 480, 81, 16))
        self.label_84.setObjectName("label_84")
        self.flange_bushing_lineEdit_excel_input = QtWidgets.QLineEdit(self.tab_7)
        self.flange_bushing_lineEdit_excel_input.setGeometry(QtCore.QRect(40, 500, 151, 22))
        self.flange_bushing_lineEdit_excel_input.setObjectName("flange_bushing_lineEdit_excel_input")
        self.flange_bushing_pushButton = QtWidgets.QPushButton(self.tab_7)
        self.flange_bushing_pushButton.setGeometry(QtCore.QRect(40, 540, 181, 28))
        self.flange_bushing_pushButton.setObjectName("flange_bushing_pushButton")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(40, 340, 181, 121))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_85 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_13.addWidget(self.label_85)
        self.line_13 = QtWidgets.QFrame(self.verticalLayoutWidget_13)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_13.addWidget(self.line_13)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_86 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_86.setObjectName("label_86")
        self.horizontalLayout_44.addWidget(self.label_86)
        self.flange_bushing_lineEdit_P_limit_applied = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.flange_bushing_lineEdit_P_limit_applied.setObjectName("flange_bushing_lineEdit_P_limit_applied")
        self.horizontalLayout_44.addWidget(self.flange_bushing_lineEdit_P_limit_applied)
        self.verticalLayout_13.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_87 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_45.addWidget(self.label_87)
        self.flange_bushing_lineEdit_FF = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.flange_bushing_lineEdit_FF.setObjectName("flange_bushing_lineEdit_FF")
        self.horizontalLayout_45.addWidget(self.flange_bushing_lineEdit_FF)
        self.verticalLayout_13.addLayout(self.horizontalLayout_45)
        self.flange_bushing_toolButton_excel_input = QtWidgets.QToolButton(self.tab_7)
        self.flange_bushing_toolButton_excel_input.setGeometry(QtCore.QRect(200, 500, 27, 22))
        self.flange_bushing_toolButton_excel_input.setObjectName("flange_bushing_toolButton_excel_input")
        self.flange_bushing_tableWidget_results = QtWidgets.QTableWidget(self.tab_7)
        self.flange_bushing_tableWidget_results.setGeometry(QtCore.QRect(240, 30, 821, 531))
        self.flange_bushing_tableWidget_results.setObjectName("flange_bushing_tableWidget_results")
        self.flange_bushing_tableWidget_results.setColumnCount(0)
        self.flange_bushing_tableWidget_results.setRowCount(0)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(40, 30, 180, 231))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_88 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_14.addWidget(self.label_88)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_89 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_46.addWidget(self.label_89)
        self.flange_bushing_lineEdit_Fcy = QtWidgets.QLineEdit(self.verticalLayoutWidget_14)
        self.flange_bushing_lineEdit_Fcy.setObjectName("flange_bushing_lineEdit_Fcy")
        self.horizontalLayout_46.addWidget(self.flange_bushing_lineEdit_Fcy)
        self.verticalLayout_14.addLayout(self.horizontalLayout_46)
        self.label_90 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_14.addWidget(self.label_90)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_91 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_47.addWidget(self.label_91)
        self.flange_bushing_lineEdit_tb = QtWidgets.QLineEdit(self.verticalLayoutWidget_14)
        self.flange_bushing_lineEdit_tb.setObjectName("flange_bushing_lineEdit_tb")
        self.horizontalLayout_47.addWidget(self.flange_bushing_lineEdit_tb)
        self.verticalLayout_14.addLayout(self.horizontalLayout_47)
        self.label_92 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_14.addWidget(self.label_92)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_93 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_48.addWidget(self.label_93)
        self.flange_bushing_lineEdit_tf = QtWidgets.QLineEdit(self.verticalLayoutWidget_14)
        self.flange_bushing_lineEdit_tf.setObjectName("flange_bushing_lineEdit_tf")
        self.horizontalLayout_48.addWidget(self.flange_bushing_lineEdit_tf)
        self.verticalLayout_14.addLayout(self.horizontalLayout_48)
        self.label_94 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_14.addWidget(self.label_94)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_95 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_49.addWidget(self.label_95)
        self.flange_bushing_lineEdit_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_14)
        self.flange_bushing_lineEdit_d.setObjectName("flange_bushing_lineEdit_d")
        self.horizontalLayout_49.addWidget(self.flange_bushing_lineEdit_d)
        self.verticalLayout_14.addLayout(self.horizontalLayout_49)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 30, 261, 111))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget_7)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.pin_bolt_lineEdit_Ftu = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.pin_bolt_lineEdit_Ftu.setObjectName("pin_bolt_lineEdit_Ftu")
        self.horizontalLayout_4.addWidget(self.pin_bolt_lineEdit_Ftu)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_4.addWidget(self.label_40)
        self.pin_bolt_lineEdit_Fty = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.pin_bolt_lineEdit_Fty.setObjectName("pin_bolt_lineEdit_Fty")
        self.horizontalLayout_4.addWidget(self.pin_bolt_lineEdit_Fty)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_20.addWidget(self.label_42)
        self.pin_bolt_lineEdit_Fsu = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.pin_bolt_lineEdit_Fsu.setObjectName("pin_bolt_lineEdit_Fsu")
        self.horizontalLayout_20.addWidget(self.pin_bolt_lineEdit_Fsu)
        self.label_45 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_20.addWidget(self.label_45)
        self.pin_bolt_lineEdit_Fsy = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.pin_bolt_lineEdit_Fsy.setObjectName("pin_bolt_lineEdit_Fsy")
        self.horizontalLayout_20.addWidget(self.pin_bolt_lineEdit_Fsy)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_22.addWidget(self.label_46)
        self.pin_bolt_lineEdit_Fbu = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.pin_bolt_lineEdit_Fbu.setObjectName("pin_bolt_lineEdit_Fbu")
        self.horizontalLayout_22.addWidget(self.pin_bolt_lineEdit_Fbu)
        self.label_48 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_22.addWidget(self.label_48)
        self.pin_bolt_lineEdit_k = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.pin_bolt_lineEdit_k.setObjectName("pin_bolt_lineEdit_k")
        self.horizontalLayout_22.addWidget(self.pin_bolt_lineEdit_k)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(310, 30, 231, 111))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_49 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_8.addWidget(self.label_49)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_8.addWidget(self.line_8)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_50 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_25.addWidget(self.label_50)
        self.pin_bolt_lineEdit_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.pin_bolt_lineEdit_d.setObjectName("pin_bolt_lineEdit_d")
        self.horizontalLayout_25.addWidget(self.pin_bolt_lineEdit_d)
        self.label_51 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_25.addWidget(self.label_51)
        self.pin_bolt_lineEdit_gap = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.pin_bolt_lineEdit_gap.setObjectName("pin_bolt_lineEdit_gap")
        self.horizontalLayout_25.addWidget(self.pin_bolt_lineEdit_gap)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_52 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_26.addWidget(self.label_52)
        self.pin_bolt_lineEdit_ti = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.pin_bolt_lineEdit_ti.setObjectName("pin_bolt_lineEdit_ti")
        self.horizontalLayout_26.addWidget(self.pin_bolt_lineEdit_ti)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_53 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_27.addWidget(self.label_53)
        self.pin_bolt_lineEdit_tf = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.pin_bolt_lineEdit_tf.setObjectName("pin_bolt_lineEdit_tf")
        self.horizontalLayout_27.addWidget(self.pin_bolt_lineEdit_tf)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(580, 30, 231, 111))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_54 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_9.addWidget(self.label_54)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget_9)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_55 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_28.addWidget(self.label_55)
        self.pin_bolt_lineEdit_P_limit = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.pin_bolt_lineEdit_P_limit.setObjectName("pin_bolt_lineEdit_P_limit")
        self.horizontalLayout_28.addWidget(self.pin_bolt_lineEdit_P_limit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_57 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_29.addWidget(self.label_57)
        self.pin_bolt_lineEdit_P_ultimate = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.pin_bolt_lineEdit_P_ultimate.setObjectName("pin_bolt_lineEdit_P_ultimate")
        self.horizontalLayout_29.addWidget(self.pin_bolt_lineEdit_P_ultimate)
        self.verticalLayout_9.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_58 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_30.addWidget(self.label_58)
        self.pin_bolt_lineEdit_FF = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.pin_bolt_lineEdit_FF.setObjectName("pin_bolt_lineEdit_FF")
        self.horizontalLayout_30.addWidget(self.pin_bolt_lineEdit_FF)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.pin_bolt_tableWidget_results = QtWidgets.QTableWidget(self.tab_4)
        self.pin_bolt_tableWidget_results.setGeometry(QtCore.QRect(20, 170, 1051, 561))
        self.pin_bolt_tableWidget_results.setObjectName("pin_bolt_tableWidget_results")
        self.pin_bolt_tableWidget_results.setColumnCount(0)
        self.pin_bolt_tableWidget_results.setRowCount(0)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(840, 30, 231, 111))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_56 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_10.addWidget(self.label_56)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget_10)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_10.addWidget(self.line_10)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_59 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_31.addWidget(self.label_59)
        self.pin_bolt_lineEdit_excel_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.pin_bolt_lineEdit_excel_input.setObjectName("pin_bolt_lineEdit_excel_input")
        self.horizontalLayout_31.addWidget(self.pin_bolt_lineEdit_excel_input)
        self.pin_bolt_toolButton_excel_input = QtWidgets.QToolButton(self.verticalLayoutWidget_10)
        self.pin_bolt_toolButton_excel_input.setObjectName("pin_bolt_toolButton_excel_input")
        self.horizontalLayout_31.addWidget(self.pin_bolt_toolButton_excel_input)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pin_bolt_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.pin_bolt_pushButton.setObjectName("pin_bolt_pushButton")
        self.horizontalLayout_33.addWidget(self.pin_bolt_pushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_33)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lug_toolButton_excel_input = QtWidgets.QToolButton(self.tab)
        self.lug_toolButton_excel_input.setGeometry(QtCore.QRect(240, 660, 27, 22))
        self.lug_toolButton_excel_input.setObjectName("lug_toolButton_excel_input")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 480, 261, 121))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.lug_lineEdit_P_ll = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lug_lineEdit_P_ll.setObjectName("lug_lineEdit_P_ll")
        self.horizontalLayout_15.addWidget(self.lug_lineEdit_P_ll)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_19.addWidget(self.label_31)
        self.lug_lineEdit_P_ul = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lug_lineEdit_P_ul.setObjectName("lug_lineEdit_P_ul")
        self.horizontalLayout_19.addWidget(self.lug_lineEdit_P_ul)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_16.addWidget(self.label_27)
        self.lug_lineEdit_theta = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lug_lineEdit_theta.setObjectName("lug_lineEdit_theta")
        self.horizontalLayout_16.addWidget(self.lug_lineEdit_theta)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 261, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.lug_lineEdit_t = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lug_lineEdit_t.setObjectName("lug_lineEdit_t")
        self.horizontalLayout_10.addWidget(self.lug_lineEdit_t)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.lug_lineEdit_D = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lug_lineEdit_D.setObjectName("lug_lineEdit_D")
        self.horizontalLayout_12.addWidget(self.lug_lineEdit_D)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.lug_lineEdit_R0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lug_lineEdit_R0.setObjectName("lug_lineEdit_R0")
        self.horizontalLayout_8.addWidget(self.lug_lineEdit_R0)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.lug_lineEdit_W = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lug_lineEdit_W.setObjectName("lug_lineEdit_W")
        self.horizontalLayout_9.addWidget(self.lug_lineEdit_W)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_17.addWidget(self.label_28)
        self.lug_lineEdit_beta = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lug_lineEdit_beta.setObjectName("lug_lineEdit_beta")
        self.horizontalLayout_17.addWidget(self.lug_lineEdit_beta)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.lug_lineEdit_a = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lug_lineEdit_a.setObjectName("lug_lineEdit_a")
        self.horizontalLayout_11.addWidget(self.lug_lineEdit_a)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(10, 640, 81, 16))
        self.label_30.setObjectName("label_30")
        self.lug_pushButton = QtWidgets.QPushButton(self.tab)
        self.lug_pushButton.setGeometry(QtCore.QRect(10, 690, 261, 28))
        self.lug_pushButton.setObjectName("lug_pushButton")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 440, 261, 24))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.lug_lineEdit_FF = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lug_lineEdit_FF.setObjectName("lug_lineEdit_FF")
        self.horizontalLayout_18.addWidget(self.lug_lineEdit_FF)
        self.lug_lineEdit_excel_input = QtWidgets.QLineEdit(self.tab)
        self.lug_lineEdit_excel_input.setGeometry(QtCore.QRect(10, 660, 221, 22))
        self.lug_lineEdit_excel_input.setObjectName("lug_lineEdit_excel_input")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 261, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lug_lineEdit_Ftu_L = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lug_lineEdit_Ftu_L.setObjectName("lug_lineEdit_Ftu_L")
        self.horizontalLayout.addWidget(self.lug_lineEdit_Ftu_L)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lug_lineEdit_Ftu_T = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lug_lineEdit_Ftu_T.setObjectName("lug_lineEdit_Ftu_T")
        self.horizontalLayout.addWidget(self.lug_lineEdit_Ftu_T)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lug_lineEdit_Fty_L = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lug_lineEdit_Fty_L.setObjectName("lug_lineEdit_Fty_L")
        self.horizontalLayout_2.addWidget(self.lug_lineEdit_Fty_L)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.lug_lineEdit_Fty_T = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lug_lineEdit_Fty_T.setObjectName("lug_lineEdit_Fty_T")
        self.horizontalLayout_2.addWidget(self.lug_lineEdit_Fty_T)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lug_tableWidget_results = QtWidgets.QTableWidget(self.tab)
        self.lug_tableWidget_results.setGeometry(QtCore.QRect(290, 40, 771, 681))
        self.lug_tableWidget_results.setObjectName("lug_tableWidget_results")
        self.lug_tableWidget_results.setColumnCount(0)
        self.lug_tableWidget_results.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Bearing Properties"))
        self.label_6.setText(_translate("MainWindow", "d: "))
        self.label_7.setText(_translate("MainWindow", "D"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.label_9.setText(_translate("MainWindow", "C"))
        self.label_10.setText(_translate("MainWindow", "Allowable P Radial (N)"))
        self.label_11.setText(_translate("MainWindow", "Allowable P axial"))
        self.label_17.setText(_translate("MainWindow", "Applied P Radial (N)"))
        self.label_33.setText(_translate("MainWindow", "Fitting Factor"))
        self.label_32.setText(_translate("MainWindow", "Excel Input"))
        self.bearing_toolButton_excel_input.setText(_translate("MainWindow", "..."))
        self.bearing_pushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bearing"))
        self.label_34.setText(_translate("MainWindow", "Excel Input"))
        self.plain_bushing_toolButton_excel_input.setText(_translate("MainWindow", "..."))
        self.label_37.setText(_translate("MainWindow", "Material Properties"))
        self.label_12.setText(_translate("MainWindow", "Fcy"))
        self.label_38.setText(_translate("MainWindow", "Bush Thickness"))
        self.label_21.setText(_translate("MainWindow", "t (Bush)"))
        self.label_39.setText(_translate("MainWindow", "Lug Females Thickness"))
        self.label_41.setText(_translate("MainWindow", "t (Lug)"))
        self.label_43.setText(_translate("MainWindow", "Inner diameter"))
        self.label_44.setText(_translate("MainWindow", "d "))
        self.label_35.setText(_translate("MainWindow", "Applied Force"))
        self.label_36.setText(_translate("MainWindow", "P_limit"))
        self.label_47.setText(_translate("MainWindow", "Fitting Factor FF:"))
        self.plain_bushing_pushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Plain Bushing"))
        self.label_84.setText(_translate("MainWindow", "Excel Input"))
        self.flange_bushing_pushButton.setText(_translate("MainWindow", "Run"))
        self.label_85.setText(_translate("MainWindow", "Applied Force"))
        self.label_86.setText(_translate("MainWindow", "P_limit"))
        self.label_87.setText(_translate("MainWindow", "Fitting Factor FF:"))
        self.flange_bushing_toolButton_excel_input.setText(_translate("MainWindow", "..."))
        self.label_88.setText(_translate("MainWindow", "Material Properties"))
        self.label_89.setText(_translate("MainWindow", "Fcy"))
        self.label_90.setText(_translate("MainWindow", "Bush Thickness"))
        self.label_91.setText(_translate("MainWindow", "t (Bush)"))
        self.label_92.setText(_translate("MainWindow", "Lug Females Thickness"))
        self.label_93.setText(_translate("MainWindow", "t (Lug)"))
        self.label_94.setText(_translate("MainWindow", "Inner diameter"))
        self.label_95.setText(_translate("MainWindow", "d "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Flange Bushing"))
        self.label_23.setText(_translate("MainWindow", "Material Properties"))
        self.label_24.setText(_translate("MainWindow", "Ftu"))
        self.label_40.setText(_translate("MainWindow", "Fty"))
        self.label_42.setText(_translate("MainWindow", "Fsu"))
        self.label_45.setText(_translate("MainWindow", "Fsy"))
        self.label_46.setText(_translate("MainWindow", "Fbu"))
        self.label_48.setText(_translate("MainWindow", "k"))
        self.label_49.setText(_translate("MainWindow", "Geometry"))
        self.label_50.setText(_translate("MainWindow", "Pin diameter d:"))
        self.label_51.setText(_translate("MainWindow", "Gap:"))
        self.label_52.setText(_translate("MainWindow", "Male thickness lug ti:"))
        self.label_53.setText(_translate("MainWindow", "Feale thickness lug tf:"))
        self.label_54.setText(_translate("MainWindow", "Applied Forces"))
        self.label_55.setText(_translate("MainWindow", "P Limit:"))
        self.label_57.setText(_translate("MainWindow", "P Ultimate:"))
        self.label_58.setText(_translate("MainWindow", "Fiftting Facto FF:"))
        self.label_56.setText(_translate("MainWindow", "Execute"))
        self.label_59.setText(_translate("MainWindow", "Excel Input"))
        self.pin_bolt_toolButton_excel_input.setText(_translate("MainWindow", "..."))
        self.pin_bolt_pushButton.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Pin bolt"))
        self.lug_toolButton_excel_input.setText(_translate("MainWindow", "..."))
        self.label_25.setText(_translate("MainWindow", "Applied Force"))
        self.label_26.setText(_translate("MainWindow", "P_limit"))
        self.label_31.setText(_translate("MainWindow", "P_ultimate"))
        self.label_27.setText(_translate("MainWindow", "theta (deg)"))
        self.label_4.setText(_translate("MainWindow", "Lug geometry"))
        self.label_18.setText(_translate("MainWindow", "Thickness t:"))
        self.label_20.setText(_translate("MainWindow", "Hole Diameter D:"))
        self.label_15.setText(_translate("MainWindow", "Lug Diameter R0:"))
        self.label_16.setText(_translate("MainWindow", "Equivalent Lug width W: "))
        self.label_28.setText(_translate("MainWindow", "Tapered angle beta (deg):"))
        self.label_19.setText(_translate("MainWindow", "Minimum distance hole- tapered contour "))
        self.label_22.setText(_translate("MainWindow", "a:"))
        self.label_30.setText(_translate("MainWindow", "Excel Input"))
        self.lug_pushButton.setText(_translate("MainWindow", "Run"))
        self.label_29.setText(_translate("MainWindow", "Fitting Factor FF:"))
        self.label.setText(_translate("MainWindow", "Material Properties"))
        self.label_2.setText(_translate("MainWindow", "Ftu_L"))
        self.label_13.setText(_translate("MainWindow", "Ftu_T"))
        self.label_3.setText(_translate("MainWindow", "Fty_L"))
        self.label_14.setText(_translate("MainWindow", "Fty_T"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lug Analysis"))

